---
- name: Set bootstrap validator host
  ansible.builtin.set_fact:
    bootstrap_host: "{{ groups['genesis'][0] }}"

# Check that dependencies are installed
- name: Check dependencies
  ansible.builtin.import_tasks: dependencies.yml

- name: Create validator keys
  ansible.builtin.import_tasks: keygen.yml
  when:
  - override_keygen | default(false)
  - inventory_hostname != bootstrap_host

- name: Gather cluster facts
  ansible.builtin.import_tasks: gather.yml

- name: Fund non-bootstrap validator keys
  ansible.builtin.import_tasks: fund.yml
  when:
    - override_keygen | default(false)
    - inventory_hostname == bootstrap_host

- name: Set cluster entrypoint
  ansible.builtin.set_fact:
    fd_entrypoint: "{{ hostvars[bootstrap_host]['gossip_host'] }}:{{ gossip_port }}"

- name: Copy the config file
  ansible.builtin.template:
    src: fd_config.toml.j2
    dest: "{{ fd_config_file }}"
    owner: "{{ fd_user }}"
    group: "{{ fd_user }}"
    mode: 0644

- name: Join firedancer validators to existing cluster
  ansible.builtin.import_tasks: join.yml
  when:
    - inventory_hostname != bootstrap_host
