---
- name: Set solana validator and epoch info commands
  ansible.builtin.set_fact:
    labs_validator: "{{ labs_bindir }}/solana-validator"
    labs_solana_entrypoint: "{{ hostvars[bootstrap_host]['labs_gossip_host'] }}:{{ labs_gossip_port }}"
    solana_cmd: "{{ labs_bindir }}/solana -u http://{{ hostvars[bootstrap_host]['labs_gossip_host'] }}:{{ labs_rpc_port }}"

- name: Copy labs join validator template to system
  become: yes
  ansible.builtin.template:
    src: labs_validator.service.j2
    dest: /etc/systemd/system/fd_e2e_labs_validator.service

- name: Start labs service if not already running
  become: yes
  ansible.builtin.systemd:
    name: fd_e2e_labs_validator
    state: started
    daemon_reload: true

- name: Create vote account
  ansible.builtin.shell: >
    {{ solana_cmd }} create-vote-account
    -k {{ labs_keys_dir }}/id.json
    --allow-unsafe-authorized-withdrawer
    {{ labs_keys_dir }}/vote.json {{ labs_keys_dir }}/id.json {{ labs_keys_dir }}/id.json
  register: slot_value
  until: slot_value.rc == 0
  retries: 5
  delay: 1

- name: Create stake account
  ansible.builtin.shell: >
    {{ solana_cmd }} create-stake-account
    -k {{ labs_keys_dir }}/id.json
    {{ labs_keys_dir }}/stake.json {{ stake_sol }}

- name: Delegate stake 
  ansible.builtin.shell: >
    {{ solana_cmd }} delegate-stake
    -k {{ labs_keys_dir }}/id.json
    {{ labs_keys_dir }}/stake.json {{ labs_keys_dir }}/vote.json
