---
- name: Set solana validator and epoch info commands
  ansible.builtin.set_fact:
    labs_validator: "{{ labs_bindir }}/solana-validator"
    solana_entrypoint: "{{ hostvars[bootstrap_host]['gossip_host'] }}:{{ gossip_port }}"
    solana_cmd: "{{ labs_bindir }}/solana -u http://{{ hostvars[bootstrap_host]['gossip_host'] }}:{{ rpc_port }}"

- name: Remove old ledger
  become: yes
  ansible.builtin.file:
    path: "{{ ledger }}"
    state: absent

- name: Create ledger
  ansible.builtin.file:
    path: "{{ ledger }}"
    state: directory

- name: Copy labs join validator template to system
  become: yes
  ansible.builtin.template:
    src: labs_validator.service.j2
    dest: /etc/systemd/system/fd_e2e_labs_validator.service

- name: Start labs service if not already running
  become: yes
  ansible.builtin.systemd:
    name: fd_e2e_labs_validator
    state: started
    daemon_reload: true

- name: Create vote account
  ansible.builtin.shell: >
    {{ solana_cmd }} create-vote-account
    -k {{ keys_dir }}/id.json
    --allow-unsafe-authorized-withdrawer
    {{ keys_dir }}/vote.json {{ keys_dir }}/id.json {{ keys_dir }}/id.json

- name: Create stake account
  ansible.builtin.shell: >
    {{ solana_cmd }} create-stake-account
    -k {{ keys_dir }}/id.json
    {{ keys_dir }}/stake.json {{ stake_sol }}

- name: Delegate stake 
  ansible.builtin.shell: >
    {{ solana_cmd }} delegate-stake
    -k {{ keys_dir }}/id.json
    {{ keys_dir }}/stake.json {{ keys_dir }}/vote.json
