---
- name: Set bootstrap validator host
  ansible.builtin.set_fact:
    bootstrap_host: "{{ groups['genesis'][0] }}"

# Check that dependencies are installed
- name: Check dependencies
  ansible.builtin.import_tasks: dependencies.yml

- name: Create validator keys
  ansible.builtin.import_tasks: keygen.yml
  when:
  - override_keygen | default(false)
  - inventory_hostname != bootstrap_host

- name: Gather cluster facts
  ansible.builtin.import_tasks: gather.yml

- name: Fund non-bootstrap validator keys
  ansible.builtin.import_tasks: fund.yml
  when:
    - override_keygen | default(false)
    - inventory_hostname == bootstrap_host

- name: Join labs validators to existing cluster
  ansible.builtin.import_tasks: join.yml
  when: 
    - inventory_hostname != bootstrap_host
