---
- name: Set genesis host
  ansible.builtin.set_fact:
    genesis_host: "{{ groups['genesis'][0] }}"

- name: Create validator keys
  ansible.builtin.import_tasks: keygen.yml
  when: override_keygen | default(false)

- name: Gather cluster facts
  ansible.builtin.import_tasks: gather.yml

- name: Run the bootstrap validator
  ansible.builtin.import_tasks: bootstrap.yml
  when: 
    - inventory_hostname == genesis_host

- name: Join labs validators to existing cluster
  ansible.builtin.import_tasks: join.yml
  when: 
    - inventory_hostname != genesis_host
