---
# TODO: sanity check host declarations
all:
  hosts:

  children:
    fd_build:
      hosts:

    labs_build:
      hosts:

    genesis:
      hosts:

    fd_run:
      hosts:

    labs_run:
      hosts:
